api_key_env: CROWDIN_API_KEY
project_identifier: rancher-ui
base_path: /translations
preserve_hierarchy: false

files:
  - source: en-us.yaml
    dest: /ui.yaml
    translation: '%locale%.yaml'
    type: yaml
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        de-DE: de-de
        en-US: en-us
        es-ES: es-es
        fa-IR: fa-ir
        fr-FR: fr-fr
        it-IT: it-it
        ja-JP: ja-jp
        hu-HU: hu-hu
        ko-KR: ko-kr
        nb-NO: nb-no
        nl-NL: nl-nl
        pt-BR: pt-br
        ru-RU: ru-ru
        sv-SE: sv-se
        zh-CN: zh-hans
        zh-TW: zh-hant
